### ISSUE TITLE
New Rule: analyzer dependencies should not have a fixed version

### ISSUE THREAD

**Issue by Corniel** [dotnet-project-file-analyzers/dotnet-project-file-analyzers#123]
Having to update the version of analyzers is not worth the effort most of the time. Furthermore, it will not change any assembly that is compiled.

**Comment by CptWesley** [comment]
I disagree with this rule, especially the latter part.

If we have 2 dependencies: A (some analyzer) and B (not an analyzer):

```
<PackageReference Include="A" Version="*" PrivateAssets="all"/>
<PackageReference Include="B" Version="1.0.0" />
```

If both `A` and `B` have a dependency on `C`, this could lead to the version of `C` used at runtime being unexpectedly upgraded due to `B` implicitly selecting a higher version due to it's floating version.
